name: Animator Alex
favicon: null
layout_spectrum: 0.7637585916090757
typography_spectrum: 0.4333241449203342
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.9533400691580027
  lightness: 0.8145877900533378
  saturation: 0.05304865096695721
  rhythmicContrast: 0.5272125096525997
purpose: []
